### ISSUE TITLE
Appropriate to point agencies here to ask for help?

### ISSUE THREAD

**Issue by konklone** [GSA/https#10]
Would this make an acceptable support forum and permalink to point agencies to, who want to move to HTTPS and could use some expert advice?

**Comment by alex** [comment]
Speaking for myself, I'm happy to provide advice here. I wonder if at least some agencies would want to do stuff in private (e.g. discussing their contracts with akamai).

**Comment by konklone** [comment]
>  I wonder if at least some agencies would want to do stuff in private (e.g. discussing their contracts with akamai).

Oh, I'm sure they would. My thinking is that whatever advice we can get out in public will make useful permalinks for people, and more easily inform the guide work.

**Comment by gbinal** [comment]
@konklone - Yes, I definintely think it is.

**Comment by konklone** [comment]
I didn't end up including it in [18F's HSTS post](https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/), as it wasn't built out enough, but I think we can definitely plan to send people here in the next exciting batch of announcements.
