### ISSUE TITLE
Comment from the American Civil Liberties Union

### ISSUE THREAD

**Issue by csoghoian** [GSA/https#106]
We submitted a 6 page formal comment a couple days ago, which can be found on [our website](https://www.aclu.org/sites/default/files/field_document/aclu_comment_on_https_only_standard_-_submitted.pdf).

**Comment by rduerr** [comment]
Please read  #107 opened 2 days ago by jhourcle - they represent the situation in science and for the general public really very well...

**Comment by csoghoian** [comment]
In response to our letter (and the subsequent media coverage), Rep. Joaquin Castro has [introduced legislation](http://amendments-rules.house.gov/amendments/CAS3242015140249249.pdf) to require IGs to encrypt their whistleblower hotlines.
