### ISSUE TITLE
Enable HSTS with includeSubDomains on .gov

### ISSUE THREAD

**Issue by keeleysam** [GSA/https#111]
To really enforce this, a HSTS policy should be set for the .gov TLD with includeSubdomains and preload.  This is mentioned as a possibility in the docs, but it should be added to the policy.  This won't be able to be set by the normal methods, but the Chromium developers could easily add it.

Agencies can individually send these headers and even get preloaded, but this is unlikely to actually happen and requires either an initial plaintext connection which can be intercepted and hopefully redirects to HTTPS or getting individual domains on the preload list.  

Some agencies may run servers which make it difficult to add the headers, or they may not run web servers on their domains without www.

For example, if I navigate to http://www.example.gov and that redirects me to https://www.example.gov which has HSTS with includeSubdomains, this really only means subdomains of www.example.gov.  Therefore, if I then went to http://www2.example.gov, my browser would be happy to load that over plaintext.

The workaround for that means web servers need to be run at the root domain and all pages need to include something silly like `<img src="https://example.gov/blank.gif">`.  Otherwise, you'll never really get it everywhere.

Setting it for .gov as a whole will make this policy have real weight.

For those agencies who run plaintext intranet and can't setup a simple nginx proxy, they can use enterprise policy to override this for subdomains to selectively allow plaintext.  As an example, enterprise policy could be used to set an HSTS header with max-age of 0 for the permitted domains.  See https://code.google.com/p/chromium/issues/detail?id=158883

Extra bonus points for key pinning, but that's for another day.

**Comment by konklone** [comment]
@keeleysam The docs do mention this as a possibility, and [18F's post on HSTS preloading](https://18f.gsa.gov/2015/02/09/the-first-gov-domains-hardcoded-into-your-browser-as-all-https/) mentions it as an awesome goal.

However, you should be aware that `.gov` encompasses [more than the federal government](https://18f.gsa.gov/2014/12/18/a-complete-list-of-gov-domains/). States, counties, localities, native tribes, they all use `.gov`. There are local libraries and power plants that (somehow) have a second-level `.gov` domain. The federal government has ~1,350 domains, and there are ~5,300 in total.

I don't mean to say the problem's intractable -- I think it'll happen, and [pulse.cio.gov](https://pulse.cio.gov/) specifically calls out individual federal domains which preload, as a way of building momentum. But it's got to be addressed at the state and local level too, which is not something this policy can mandate.

**Comment by konklone** [comment]
I'm going to close this as something that's out of scope for this *particular* repository, while noting again that this is an excellent goal, and something that will require a lot of work outside of the federal government's direct control.
