### ISSUE TITLE
monitoring of USPTO is incomplete

### ISSUE THREAD

**Issue by oplf** [GSA/https#112]
The CIO dashboard lists a mere two web sites for the USPTO.  Neither one uses SSL as of today.  But the dashboard overlooks more than a dozen public web pages that USPTO administers, and that need SSL, and that USPTO has failed to protect with SSL.  These include:
epas.uspto.gov
etas.uspto.gov
tsdr.uspto.gov
tarr.uspto.gov
teas.uspto.gov
tess.uspto.gov
aotw.uspto.gov
patft.uspto.gov
ttabvue.uspto.gov
appft.uspto.gov
All of these web sites need to be included on the CIO dashboard.

**Comment by konklone** [comment]
Thank you, but would you mind moving this issue over to the [pulse.cio.gov issue tracker](https://github.com/18F/pulse/issues)? You could also instead comment on https://github.com/18F/pulse/issues/27, which is about tracking subdomains.

**Comment by oplf** [comment]
On 6/9/2015 10:05 AM, Eric Mill wrote:
>
> Thank you, but would you mind moving this issue over to the 
> pulse.cio.gov issue tracker <https://github.com/18F/pulse/issues>?
>

Isn't that where I posted it in the first place?  I am pretty sure I was 
on that page when I clicked on "new issue".

> You could also instead comment on 18F/pulse#27 
> <https://github.com/18F/pulse/issues/27>, which is about tracking 
> subdomains.
>

Okay I tried to do that.
