### ISSUE TITLE
OCSP stapling 

### ISSUE THREAD

**Issue by konklone** [GSA/https#122]
Implement it for https.cio.gov using nginx 1.9.2, using @agwa's excellent [OCSP stapling guide](https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx), and then update the tech guidelines page with information about it.

**Comment by konklone** [comment]
It seems to me like there's still more advancement that has to happen in the browser and CA world (e.g. multistapling, must-staple, and short-lived certs that aren't checked for revocation) before this is worth pushing hard on. Happy to re-open if anyone wants to discuss further.

**Comment by konklone** [comment]
Well! This makes me think there could, either now or soon, be something worth including:

https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/

Mozilla has implemented support for OCSP Must-Staple, which is specified through a [TLS Feature Extension](https://tools.ietf.org/html/rfc7633) (a new standard as of October 2015). So the CA includes the extension in the certificate they issue which basically says "this certificate should only be considered valid if OCSP information was stapled alongside it".

It'd be nice to hear from at least one other browser what their plans are, but since OCSP stapling itself is already widely supported, this may make it worth documenting and encouraging.

**Comment by AGWA** [comment]
Before you enable OCSP stapling, you may want to read through this Twitter conversation from this morning: https://twitter.com/sleevi_/status/669566272003112960

**Comment by konklone** [comment]
Thanks, @AGWA -- that is a super enlightening conversation. 

@pzb Do you have any idea how Amazon is implementing OCSP stapling at scale for CloudFront? Is it vanilla nginx, or is there work being done to make up for the problems with current open source implementations?

**Comment by grandamp** [comment]
I'd like to assist with guidance, [as stapling is also enabled by default in IIS](http://news.netcraft.com/archives/2013/07/19/microsoft-achieves-world-domination-in-ocsp-stapling.html).  From a customer experience perspective, wouldn't this lead to better performance?

**Comment by konklone** [comment]
Sure would, on browsers other than Chrome, anyway. I'm happy to add a section to the Technical Guidelines section (and add OCSP stapling support to https.cio.gov itself) -- any resources or things which should go into it?

**Comment by J0WI** [comment]
Must-Staple is now also supported by Let's Encrypt and the Certbot client.

**Comment by konklone** [comment]
Handled by our cloud infrastructure.
