### ISSUE TITLE
add mention of the https-help listserve 

### ISSUE THREAD

**Issue by gbinal** [GSA/https#130]
Is this on the website and I'm missing it?  

Otherwise, any preference for where it goes?  I'd say on the resources page.

**Comment by konklone** [comment]
Yeah, top of the resources page. Want to kick it off with a PR?

**Comment by gbinal** [comment]
Sure thing - [here you go](https://github.com/GSA/https/pull/132).  Feel free to edit.

**Comment by gbinal** [comment]
Closing this in favor of #132
