### ISSUE TITLE
Broken link in https guide

### ISSUE THREAD

**Issue by bengolder** [GSA/https#135]
The link below is broken.

**[nginx configuration for https.cio.gov](https://github.com/GSA/https/blob/configs/deploy/site.conf)**
(https://github.com/GSA/https/blob/configs/deploy/site.conf)

 Found it [here](https://github.com/GSA/https/blob/master/resources/implementing-https-links.md).

**Comment by konklone** [comment]
Thanks for catching that! I added the `site.conf` file [to the repo](https://github.com/GSA/https/blob/master/deploy/site.conf), and updated the link [on the resources list](https://github.com/GSA/https/blob/master/resources/implementing-https-links.md).
