### ISSUE TITLE
Update link to Microsoft's announcement on SHA-1 deprecation?

### ISSUE THREAD

**Issue by anand-bhat** [GSA/https#157]
In https://https.cio.gov/technical-guidelines/, the link to "Microsoft" (http://blogs.technet.com/b/pki/archive/2013/11/12/sha1-deprecation-policy.aspx) in the sentence "SHA-1 has been shown to have serious weaknesses, and so browser and OS providers like Google, **Microsoft**, and Mozilla have announced timelines to deprecate SHA-1 in favor of the SHA-2 family of algorithms." no longer has relevant content.

The text on the page has been replaced with "Update: This page has been removed.  For the most up to date information on the Microsoft SHA1 deprecation policy please see http://aka.ms/sha1" which points to http://social.technet.microsoft.com/wiki/contents/articles/32288.windows-enforcement-of-authenticode-code-signing-and-timestamping.aspx

I wasn't sure if you'd like to update the link to use the new page as it has a lot more content than a simple announcement.

**Comment by konklone** [comment]
Good catch, I updated this in https://github.com/GSA/https/commit/e0e0bd38bf37d2c77fcb6d42175d976f203683fc and mentioned you in the commit message.
