### ISSUE TITLE
Import useful concepts/code from certlint and the crt.sh service?

### ISSUE THREAD

**Issue by bknowles** [GSA/https#177]
Folks,

Got this in the most recent Fiesty Duck TLS news from the folks at SSLabs:

> Peter Bowen from Amazon developed the tool certlint to check for several common errors in X.509 certificates. The source code is available on Github and the tool has been integrated into the crt.sh service, a web interface that provides access to the Certificate Transparency logs. Certlint identified several hundred errors and several thousand warnings in valid certificates.

Don't know if this would be useful to you, but thought I'd point it out and let you take a look at it to see if there was anything of interest.

**Comment by konklone** [comment]
That's a solid idea. We can incorporate links to @pzb's certlint on a few relevant pages. Thanks for suggesting this, @bknowles!
