### ISSUE TITLE
"So you've registered a new domain"

### ISSUE THREAD

**Issue by konklone** [GSA/https#191]
A page or section on what a new registrant of a .gov or .mil domain (or any TLD an agency uses) should do after they get their registration.

When it comes to M-15-13, using `domain.mil` as the example, it's:
- Set a DNS record for domain.mil (www.domain.mil is optional).
- Get a certificate for domain.mil and www.domain.mil, and point https://domain.mil at any content (could be a blank white page).
- Have http://domain.mil redirect to https://domain.mil.
- Add a `Strict-Transport-Security: max-age=31536000; includeSubDomains; preload` HTTP header to https://domain.mil
- Submit it to the form on https://hstspreload.appspot.com.

This gets the domain into the queue so that by the time whatever web service the domain owner plans to roll out is launched, the domain is already HTTPS-only, even for the first time people visit it. This also means that as new subdomains are added, be they intranet or not, they will have to support HTTPS in order to function.

Besides being good practice, this will help mitigate situations where the government campaigns to have citizens visit a newly registered domain on launch, having all those citizens type it into their URL bar, and subjecting them all to the risk of redirection or other malicious compromise of the connection.

It also would make a good candidate for dotgov.gov to link to for new .gov registrants (be they federal or not).

**Comment by chavellacinema160** [comment]
Trying

**Comment by DXGLdotinfo** [comment]
Are domains obtained via seizure via law enforcement or similar agencies exempt from this standard?

**Comment by konklone** [comment]
This is basically covered by this: https://home.dotgov.gov/management/security-best-practices/
