### ISSUE TITLE
Foreign language translations

### ISSUE THREAD

**Issue by konklone** [GSA/https#204]
We should be readable and useful for citizens and governments of other countries. 

Translating everything isn't necessary; I think `/` and `/everything/` are the most important pages to translate. The `/` page never changes, and `/everything/` almost never changes, making it easy to do this as a one-time thing. I'd be fine with committing to not change `/everything/` in substantive ways (other than removals, which would be easy to replicate).

I don't know what the most relevant languages to focus on are. I imagine it'll depend on who we can find who's interested in translating.

**Comment by konklone** [comment]
We should be readable and useful for citizens and governments of other countries. 

Translating everything isn't necessary; I think `/` and `/everything/` are the most important pages to translate. The `/` page never changes, and `/everything/` almost never changes, making it easy to do this as a one-time thing. I'd be fine with committing to not change `/everything/` in substantive ways (other than removals, which would be easy to replicate).

I don't know what the most relevant languages to focus on are. I imagine it'll depend on who we can find who's interested in translating.

**Comment by obrien-j** [comment]
@konklone We may investigate what would be involved in doing i8n across the board, if you think that's a PR you might be interested in taking. We'll need a bilingual site if we roll this out within Canada.

**Comment by konklone** [comment]
@obrien-j If you think you'll be using this repository for your work, we'd likely happily take a PR so that we can both be working from the same base. 

But are you really likely to rely directly on this repository? I would assume that the Canadian government guidance would be different in some areas.

**Comment by obrien-j** [comment]
Ignore previous. I flipped over from pulse and didn't check the URL. Comments were related to pulse as a framework. 
Nothing to see here! Carry on!

**Comment by konklone** [comment]
:+1:

@obrien-j We've had enough Pulse forks now that I think we're really overdue for a modular Pulse core that can be extended with specific measurements. Happy to help support on that kind of work as I can.

**Comment by konklone** [comment]
Translating `/` would require significant coordination with OMB, and is unlikely to happen any time soon.
