### ISSUE TITLE
Referrer policy

### ISSUE THREAD

**Issue by elucify** [GSA/https#208]
Since we moved our interactive web traffic to https, we've received a
request from an external website that receives a lot clickthroughs
from our site. They complain that they have lost referrers to their
http pages, so their analytics aren't as good as they were.

That behavior is by design: browsers won't send referrers from an https URL
to an http URL, since that could leak information about the user. The
default behavior for a browser when linking from an https URL to
another https URL, even on a different domain, is to send the
referrer.

The person who contacted me about the referrers would like us to add
meta tags, <meta name="referrer" content="always"/>, which would
restore those referrers. Yet this also seems like a privacy leak; we'd
be passing on information about the user to a third party.

Looking over commentary on the <meta name="referrer"> element, it
seems to me that the most reasonable compromise should be <meta
name="referrer" content="origin-when-cross-origin"/>. That would
provide full referrers when linking from our origin to itself, and
just the scheme, host, and port when linking (or POSTing) across
origins. So our customer would know their user came from us, but not
where on our site. The default behavior is consistent with the
referrer directive "none-when-downgrade": the full referrer is sent,
except when going from https -> http.

Does cio.gov <http://cio.gov> provide guidance on this?

For the moment, our site will have to live with the default behavior,
because putting that <meta> element everywhere is not a simple
job. But we'd like to know if there has been any policy discussion
about what to do with referrers. It seems to me,
origin-when-cross-origin would be a reasonable compromise, in the
spirit of the OMB memorandum.

**Comment by dnesting** [comment]
Hi Mark.  Super excited that you're thinking about the privacy of your users.  I don't think the OMB guidance covers this.  Moving to SSL correctly sets the default amount of information shared in Referer headers to nothing, which means moving from nothing to something requires consideration and positive action.

My opinion is that `origin-when-cross-origin` seems reasonable if:
- your off-site links from these pages are known
- the nature of your site doesn't have privacy implications (i.e., you are not `hiv-clinic-finder.gov`)
- you don't have rare links from pages that have privacy implications (i.e., you don't have a `/hiv-clinic-finder` page on your site that is the only page that includes map tiles from a third party)

**Comment by konklone** [comment]
@elucify Please check out #214 and let me know if it addresses the concern, and provides a useful permalink.

**Comment by konklone** [comment]
> For the moment, our site will have to live with the default behavior, because putting that element everywhere is not a simple job. 

@elucify The Referrer Policy spec defines [multiple delivery mechanisms](https://www.w3.org/TR/referrer-policy/#referrer-policy-delivery), including an HTTP header. Would that be an easier way to set the referrer policy in a central place, instead of going around and updating all your HTML templates?

**Comment by elucify** [comment]
Yes, the HTTP header would be easier for our servers.

The advice in the PR looks great. However, I may not be the only one that could benefit from the advice about the HTTP header (as an alternate way to indicate referral policy.) Adding that `<meta>` tag is, in our case, certainly not the easiest road.

**Comment by konklone** [comment]
@elucify Totally, I added a commit in https://github.com/GSA/https/pull/214/commits/6a068d951055ad63d31991121e9c3b604be8b9b7 that mentions the HTTP header too. 

Merged and live:
https://https.cio.gov/faq/#how-can-an-https-site-keep-sending-referrer-information-to-linked-http-sites%3f
