### ISSUE TITLE
Deadline extension or other flexibility for http:// system identifiers in XML DOCTYPEs

### ISSUE THREAD

**Issue by elucify** [GSA/https#215]
A vast number of XML documents "in the wild" have hard-coded http:// URLs in system identifiers for DOCTYPEs and external entity declarations. For example:

```
<!DOCTYPE PUBLIC "//name" SYSTEM "http://your-favorite-agency.gov/dtds/foo.dtd">

<!ENTITY entityname SYSTEM "http://love.gov/entities/logo.xml">
```

Of secondary importance (at least for us) is the common presence of http:// URLs for `xsi:schemaLocation` and `xsi:noNamespaceSchemaLocation` attributes.

XML processors are required to find a DTD if it is specified by an XML document. External entity references must also be resolved. XML processors will try to fetch DTDs or entity text from http:// URLs when processing a document. Once we no longer support http, these processors will fail.

As far as I'm able to determine, all of the potential solutions to this problem are either entirely unworkable, or complex and expensive. The underlying technical reason is that the most widely-used tools for working with XML either do not support TLS at all (the most common UNIX toolchains, based on libxml2+libxslt), or by design, refuse to redirect http requests to https (all Java platform user agents, limited exceptions). These problems can be solved by defining custom entity resolvers and XML readers, but that requires significant programming effort for client authors.

Keep in mind that we're not just talking about government software here. We're talking about all XML processors in the world that might be used to process XML that use http:// URLs to reference DTD, XSD, or entity files hosted on US government servers. It's not just government software, services, and data that need to be updated.

Let's say we convince everyone (inside and outside government) to find and update all of their XML to use only https:// URLs. That still leaves most UNIX XML processors dead in the water, because libxml2+libxslt and associated tools (xmllint, xmlformat, etc.) aren't TLS-enabled.

When government servers redirect http:// requests (for DTDs, etc.) to https://, it's even worse, because that breaks all the Java tools, too. The vast majority of our service traffic is from Java user agents, by far. That's probably true across the entire Web, for obvious reasons.

XML wonks will say to use XML catalogs to rewrite the http:// system identifiers to https://. That's a reasonable technical solution for some scenarios, but:

1. it assumes that the document processor is TLS-enabled, so UNIX tools are still broken
2. it places a maintenance burden on government agencies _and_ maintainers of all client software that use government XML data and services
3. few developers know how to author XML catalogs (training burden), and
4. while XML 1.0 mandates XML catalog support, the APIs for managing and configuring them is not standardized, and is therefore implementation-specific (more training burden).

What about just turning off DTD and XSD validation entirely? That can work for standalone XML documents, but it doesn't solve the problem of external general entities. I can't prove but would bet that most XML documents are standalone, but don't declare that they are standalone in their XML declarations. So while this solution would usually work, the user of the client software would still have to find someone to make the fix: either their software vendor, or their IT department.

I can imagine a complex solution that uses XML catalogs or DNS fiddling to redirect DTD http traffic to a local forward proxy server, that bridges http to https. Some IT organizations might eventually figure out how to do that, but most don't have the expertise. I don't know of (and have trouble imagining) a turnkey approach for that solution.

This issue lays out what I'm finding we have to explain to both government agencies that produce XML, and authors and (worse) owners of XML client software that access government data services and legacy XML data stores. As a huge example, the NLM DTD for publishing has become a widely-supported industry standard, not just for NLM, but for much scientific article publishing in general. https:// system identifiers and/or redirections will break much of the installed base, immediately.

The best we are able to do at the moment is to tell everyone, "We're really sorry that the data services you rely on for your daily business are completely broken. Please put your business (clinical systems, publishing systems, etc.) on hold while you wait for upgrades from your ISVs, or hire and train programmers to fix these problems in your IT systems. Here are some things they can try. No promises."

Maybe I'm overthinking this, but I don't think so. We have been contacted by some of our clients whose IT systems (for example, a clinical system in a hospital that is used on a daily basis) that fail when we turn on http: to https: redirection, or change our system identifiers to use https.

It is for these reasons that we think an extension/exemption for http: DOCTYPE systems identifiers is warranted, absent better advice.

**Comment by konklone** [comment]
I filed #222 to address this issue.

**Comment by konklone** [comment]
Closing alongside #222.
