### ISSUE TITLE
Additional technical concepts

### ISSUE THREAD

**Issue by konklone** [GSA/https#22]
The other major factors to consider when deploying HTTPS.

- [x] Forward secrecy (and dhparam strength)
- [x] Server Name Indication
- [x] SHA-1 vs SHA-2
- [x] Avoid RC4
- [x] Don't support SSLv3, support TLSv1.2 (and TLSv1.0)
- [ ] Revocation and OCSP stapling
- [ ] ECDSA certificates
- [x] TLS_FALLBACK_SCSV (downgrade protection)
- [ ] Public key pinning (still experimental)
- [x] Session tickets and IDs

I think Strict Transport is worthy of its own page, as is HTTP/2 + SPDY.

**Comment by alex** [comment]
I hope you don't mind, I edited your comment for checkboxes.

**Comment by bknowles** [comment]
We also want to encourage people to generate their own custom DH params, right?

**Comment by bknowles** [comment]
And my next bugaboo is definitely OCSP stapling.  Should I do that under a separate pull request, or here?

**Comment by konklone** [comment]
@bknowles Yeah, there will need to be a section on DH params, with a greater emphasis on using 2048-bit or above than on using custom groups (though acknowledging that if you do need to use 1024-bit for a time, they'd better be custom).

How everything gets laid out isn't too important from a pull request perspective -- we can always move things around. OCSP stapling is a great next topic, and one I was going to write about -- with [SSLMate's excellent recent guide](https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx) as a reference.

**Comment by konklone** [comment]
@bknowles Also, you're very, very welcome to submit as many pieces of content here as you want. Just please be okay with us being a bit picky on language and content. Also, re: your other PR on TLSv1.0, we're not going to include additional `must`'s and `shall`'s here. The policy mandate and deprecation stuff is done for the time being, and encoded in the memo that was released today. Everything else is recommendations.

That's not to say there aren't other ways to push those recommendations. For example, if you [search pulse.cio.gov for "SSLv3"](https://pulse.cio.gov/https/domains/#q=sslv3), and click on any of the `+` buttons, you'll see that it incorporates SSL Labs grades, and calls out specific weaknesses like SSLv3, RC4, and a lack of support for TLSv1.2.

The things Pulse calls out, and the things we push for hard here, are going to be things that reflect some level of widespread attainability. For example, no one's going to be docked for not using HPKP (which is nascent and difficult), or for supporting TLSv1.0 (shutting off TLSv1.0 disables too many widely used clients).

**Comment by bknowles** [comment]
Fair enough.  I'll try to help where and when I can, and if you've got some guidelines somewhere on what needs work and what kinds of things will or won't get included, I'll be glad to try to fill in as best I can.

As it happens, I'm working on a project to help implement public and private cloud systems at a certain agency that I won't name here, and so I'm just trying to give back to the community based on the things I've found so far and trying to help tie together those bits with other bits I find that could potentially be helpful.

If anything I offer in this regard is useful, please feel free to use it where and how you see fit.

**Comment by konklone** [comment]
There are 3 left unchecked here:

- [ ] Revocation and OCSP stapling
- [ ] ECDSA certificates
- [ ] Public key pinning (still experimental)

I revamped the Technical Concepts page in #116 to focus on things we were comfortable measuring people specifically on, with clear answers about what to do. 

I think OCSP stapling is going to be an obvious one, but the standard is still nascently deployed, not widely understood, and the best reference for understanding and configuring it in major open source servers is [this recent blog post by SSLMate](https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx). Also, a major bug where nginx wasn't validating OCSP stapling expiry information was fixed [just a couple of weeks ago in nginx 1.9.2](http://nginx.org/en/CHANGES). OCSP stapling solves some privacy and performance issues, but isn't secure enough alone for clients to hard-fail on to reject expired certificates. For that, we need [an OCSP must-staple standard](https://www.grc.com/revocation/ocsp-must-staple.htm), which isn't that far advanced yet. Right now, OCSP stapling use in the .gov space seems to be somewhere around 10%.

HPKP is a powerful, dangerous standard that is definitely a great idea for security teams that are ready to take the plunge ([like Wikipedia's](https://phabricator.wikimedia.org/T92002)), but requires [some real thought and planning](https://github.com/SSLMate/sslmate/issues/10). It's not used anywhere in .gov that I'm aware or have seen in my measurements.

ECDSA is definitely a [great next step](https://blog.cloudflare.com/ecdsa-the-digital-signature-algorithm-of-a-better-internet/), though its ramifications and finer points are not super well documented. I learned more from this [Wikipedia security team thread](https://phabricator.wikimedia.org/T86654) than any blog post I've yet read. Also, right now there **are no ECDSA certs on any .gov domain or subdomain I've measured**.

I'd like to cover all 3 of the above things, but they are also in the "Yes, but..." phase of their lives -- sort of like where RC4 was in 2013. HPKP may never become a turn-it-on-and-forget-about-it thing, which is fine, and it may merit some coverage here -- I'd sort of like to see it deployed _somewhere_ in .gov first, and for deployment to spread more widely in the world, before https.cio.gov goes too far on the record about it.

Because of the above, I'm comfortable calling this issue done -- further input welcome!
