### ISSUE TITLE
Migrating an API to HTTPS

### ISSUE THREAD

**Issue by konklone** [GSA/https#25]
Publish a page about migrating an API that has an HTTP user base to HTTPS. 

Offhand, I think the outline is:

* Establish the HTTPS endpoint, with HSTS enabled.
* Update the documentation to only use the HTTPS endpoint, and to explicitly recommend migrating.
* Announce the transition plan, loudly.
* Begin clear analytics for HTTP vs HTTPS traffic.
* Update 1st party API clients and applications.
* Go around to 3rd party clients and file bugs and pull requests.
* Contact major integrators, if known, directly and tell them to use the HTTPS endpoint.
* After a time, refer to the built-up analytics, assess two reasonable deadlines: a short blackout, and a final cutover.
* Contact people the analytics shows still using the HTTP endpoint and tell them the deadlines.
* Do the short blackout and see what complaints it sends your way. 
* If no complaints, fantastic! Try a longer blackout. Still no complaints? Time for a cutover, and you're done. 
* If complaints, refer the complainants to your public warnings and deadline, and do the cutover on the deadline day.

A few things to bear in mind:

* Some (though not all) clients will follow redirects.
* HSTS will only affect supporting clients, and I've never seen a non-browser client implement HSTS.
* This also means the domain (if a second-level domain) can be freely submitted to the [browser preload list](https://hstspreload.appspot.com/), or if it's a subdomain it need not halt the submission of its parent second-level domain.
* Eventually you just have to pull the trigger.

cc @GUI @handlers

**Comment by konklone** [comment]
Ah right, so CORS requests - if one's API supports CORS, some things to bear in mind:

* You will need to put the CORS headers _on the redirect response_, as well as the response the request gets redirected to.
* CORS GET requests can follow a redirect in most browsers. 
* CORS GET requests will not follow a redirect in Android pre-4.4, all versions of iOS, and all versions of Safari. This also applies to an HSTS "internal redirect".

This also implies that the API should have analytics to determine how widespread CORS requests are, what browsers make them, and, ideally, what the referring URLs are (for ease of contacting the integrator). If mobile browsers are not a major user, then forcing a redirect should go pretty smoothly.

See some [more formal results of testing HTTPS redirects in browsers here](https://github.com/konklone/cdns-to-https#results).

**Comment by nacin** [comment]
I couldn't any resources on the Internet outlining in detail how to migrate APIs to HTTPS, along with the various factors to consider, I wrote one.

"Resources" might include pages that other services have published to help with a migration, and also their announcements. Some I just found:
 * http://code.flickr.net/2014/02/24/new-ssl-endpoints-for-the-flickr-api/
 * https://dev.twitter.com/overview/api/ssl (which made me remember that HTTPS means you can use OAuth 2 instead of OAuth 1.0a, in case you have a write API)
