### ISSUE TITLE
While performing https checking, determine which domains chain to the FCPCA prior to its removal from trust stores

### ISSUE THREAD

**Issue by tkpk** [GSA/https#257]

**Comment by tkpk** [comment]
Add this functionality to pulse so D/As may mitigate potential issues with FCPCA being removed from vendor trust stores.

**Comment by konklone** [comment]
@tkpk This repository is for the https.cio.gov website, not for Pulse or any scanning software. You may wish to look at https://github.com/18f/domain-scan for relevant code. (Pulse, the website, has not been actively maintained by GSA in years, and it's unlikely to add any new features.)
