### ISSUE TITLE
Getting HTTPS certificates

### ISSUE THREAD

**Issue by konklone** [GSA/https#26]
A page dedicated to what you need to know when getting an HTTPS certificate. This can resolve a few questions:

* Are there any US government certificate authorities I can use? (Answer: not right now, unless your website is used under controlled circumstances.)
* DV vs OV vs EV
* Favoring ease of rotation, and automation where possible
* Mention that SHA-2 and 2048-bit are the industry baseline
* Mention that ECDSA is a possibility if Windows XP doesn't need to be supported

**Comment by willchan** [comment]
Government is sensitive, and I'd be more cautious than normal about favoring specific CAs. My personal pref would be to reference several reputable sources.

**Comment by wrhwebmaster** [comment]
I believe the goal of uniformity and consistency is very important, for getting HTTP to HTTPS task accomplished.
If we cannot have a single source for all US Government to get its CERTS from, which could then be used government-wide, then at the minimum, we need to have a government-wide purchase agreement that we can all use, to buy CERTS. That would avoid pitfalls like favoring specific CAs.

**Comment by konklone** [comment]
> If we cannot have a single source for all US Government to get its CERTS from, which could then be used government-wide, then at the minimum, we need to have a government-wide purchase agreement that we can all use, to buy CERTS. That would avoid pitfalls like favoring specific CAs.

It seems to me that that would favor whatever CAs make it onto the blanket purchase agreement. I'd personally argue that that describes the situation today with Content Delivery Networks.

As it is, right now an agency can use whatever CAs they want to, including the CAs that provide certs for $16, $9, or $0/year. That seems good for efficiency, market liquidity, and cost savings to the taxpayer.

**Comment by konklone** [comment]
I updated the description with a rewrite of what I think this page should contain.

**Comment by konklone** [comment]
Fixed by #149.
