### ISSUE TITLE
Re-Activate on Federalist

### ISSUE THREAD

**Issue by gbinal** [GSA/https#261]
The cloud.gov account that hosted this website ended recently, without factoring in the continued need of https.cio.gov.  The site is still linked from numerous active policies and guidance websites, including cyber.dhs.gov, and a [number](https://github.com/18F/before-you-ship/search?q=https.cio.gov) of TTS [artifacts](https://github.com/cloud-gov/cg-site/search?q=https.cio.gov&type=code).

**Comment by alex** [comment]
It's also still widely referenced by non-.gov folks since it was so excellent!

**Comment by gbinal** [comment]
Yes!  this is happening.  Shouldn't be too long.  

FYI, I am likely to break the site first as I'm being made to [update dependencies](**https://github.com/GSA/https/issues/262**) and I'm a class A n00b.

**Comment by rustypickens** [comment]
Yes please!  I'm sure y'all saw this, but Chrome 90 will be assuming HTTPS by default next month (but falling back to HTTP if there's no secure option).  Time marches on!  And I plan on getting some more mileage out of how we led the way here ;)  Keep up the good work! #StillFiredUp

**Comment by gbinal** [comment]
Alrighty - this is done.  

https://https.cio.gov/

Plenty more to do, including working on the open issues and PRs here, and long-term sustainability for the site, but we're good for the moment.
