### ISSUE TITLE
Managing certificate expiry

### ISSUE THREAD

**Issue by konklone** [GSA/https#27]
There's no great trivial solution for monitoring certificate expiry right now. We're all trying to get there.

* Point to a few free/cheap/enterprise cert monitoring services.
* Does your CA support completely automated certificate renewal? (API? DNS-based validation?)

Point to the ambitions:

* Short-lived certificates: Google's rotating every 3 months. Try to get there.
* Very short-lived certificates: What if you rotated your cert every day, and didn't have to worry about revocation, key backup, expiry monitoring, fear of some kinds of key compromise, or even screwing up forward secrecy?

I continue to think there's a need for a service that just gives you an RSS feed of certificate warnings, that someone could plug into a generic feed->email service like [IFTTT](https://ifttt.com) or [Scout](https://scout.sunlightfoundation.com/import/feed). But that's out of scope for this ticket.

**Comment by willchan** [comment]
Out of scope for this ticket, but I wonder if one of us could whip up a service. It's a very simple monitoring service that could send emails whenever expiry approaches.

**Comment by konklone** [comment]
I've been plotting to make such a service in the back of my mind for a couple months now, when I told 18F staff I was about to start working on one. :smiley_cat: Let's take a day sometime and just do it.

**Comment by konklone** [comment]
Closing this in favor of a comprehensive certificate page in #26.
