### ISSUE TITLE
Amazon Web Services

### ISSUE THREAD

**Issue by konklone** [GSA/https#28]
How to manage HTTPS termination in Amazon Web Services:

* An Amazon EC2 instance directly. (Refer to termination via Haproxy, nginx, Apache, IIS, or whatever.) 
* An Amazon ELB. Either: a TCP passthrough (don't terminate on the ELB), or a recommended set of options for ELBs to terminate with the best possible settings. A discussion of what ELBs can and can't do for you when they terminate (e.g. fewer controls, doesn't require SNI).
* An Amazon CloudFront distribution. Discuss: communicating via HTTPS to the backend, what tradeoffs you make (e.g. lack of SPDY support, SNI cost, 2048-bit max keylength).

There should probably be a discussion of Amazon's [CloudHSM](http://aws.amazon.com/cloudhsm/) and [Key Management Service](http://aws.amazon.com/kms/) offerings, but I haven't used either of them.

**Comment by willchan** [comment]
Should we talk about the [TIC](http://www.dhs.gov/trusted-internet-connections) at all? I've run up against it a lot, and I suspect lots of other govt agencies have too. This affects termination at AWS, as opposed to DHS. Maybe this is a separate issue. I didn't see any govt agency except perhaps one bring it up.

**Comment by konklone** [comment]
cc @NoahKunin for TIC wisdom.

My initial reaction is that that should be separate. I know the TICs exist, but I've spoken to plenty of government IT staff around the government whose Apache, nginx, and CDN configurations determine their TLS termination quality.

**Comment by konklone** [comment]
Closing in favor of #30.

**Comment by NoahKunin** [comment]
@willchan we actually got funded recently to "solve" that issue. Should have more updates soon.

**Comment by willchan** [comment]
Huge!
