### ISSUE TITLE
Ways to Help Agencies

### ISSUE THREAD

**Issue by gbinal** [GSA/https#3]
This issue is for brainstorming ways to help agencies implement a proposed requirement to enable HTTPS.

**Comment by gbinal** [comment]
* A github-hosted hub similar to the Open Data Policy's [Project Open Data](https://project-open-data.cio.gov).  Including guidance, FAQ, a couple of webinars, etc.  
* Offer of free consults from 18F.

**Comment by gbinal** [comment]
> GSA provide contract vehicles for site termination (eg via cloud flare and Akamai)

**Comment by gbinal** [comment]
Is there a feasible shared service offering?

**Comment by konklone** [comment]
SSL is unfortunately a tough thing to offer a technical shared service around. The two pieces of instrumentation are: the termination (e.g. at a CDN or proxy), and the certificate issuance (at a CA).

SSL termination happens at the outermost network layer. So For example, we could resell Amazon CloudFront to agencies to aid in termination, if that's easier for them than using a contract vehicle themselves. But then you're in control of their entire outermost network layer, and so from a security/operations standpoint, you're essentially hosting their entire website. There's no way for us to offer *just* the SSL part of the service.

Offering a shared service on top of an API-oriented CA or CA reseller, like SSLMate, is an intriguing idea. That too would involve a fair amount of work, and potentially us handling private key material. If we didn't handle private key material, then we'd essentially be no more convenient than an agency using SSLMate or another CA themselves.

**Comment by NoahKunin** [comment]
I think the work we've already done to make SSLMate work with bulk purchasing is the "shared service". They only other thing we could do is for them to accept purchase orders instead of cards, which might be difficult for a small business.

The only other thing we could do is help interact with potential APIs the other major providers have. But given what I know about Symantec, for example, that's not an effective use of our time (ex: they requires a _local key_ on each machine).

I think a guidance what settings to select / how to install is the primary thing. If I'm not mistaken, we already have a vehicle for Akamai, CloudFront is part of the new AWS vehicle, so we just need to hit CloudFlare and Fastly to get the wide majority of the market.

**Comment by NoahKunin** [comment]
...confirmed, we have Akamai on Schedule already.

**Comment by konklone** [comment]
> I think guidance what settings to select / how to install is the primary thing.

And the 18f/tls-standards repo needs some serious updating to do better at that. That's an existing TODO for me, at least.

> I think the work we've already done to make SSLMate work with bulk purchasing is the "shared service". 

We should document our use of SSLMate, via blog post and/or markdown doc, to make it easier and less scary for people.

**Comment by dnesting** [comment]
I think a "quick start" guide would be a good approach for at least some of this.  Get an idea of the various system configurations in use among agencies, and then draw up some typical strategies to getting those systems migrated to SSL.  Where possible, provide sample configurations and point implementers to established business relationships with certificate providers and Akamai/Cloudfront/etc.

**Comment by dnesting** [comment]
Tools for testing the HTTPS site and validating that it's working might be useful here as well.  That is, running through the content on the site hunting for mixed content situations or links pointing to the HTTP site, etc.

**Comment by gbinal** [comment]
> Automate the inclusion of SSL into the domain registration/renewal.

**Comment by konklone** [comment]
I took a few things from this thread:

- [ ] Document certificate issuance with SSLMate
- [ ] Sample configurations
- [ ] Available CDNs
- [ ] Links/descriptions for HTTPS testing tools, e.g. mixed content scanning

Closing in favor of tickets that will include those things.
