### ISSUE TITLE
Apache configuration overview

### ISSUE THREAD

**Issue by konklone** [GSA/https#31]
Refer to existing resources (help?) as much as possible.

**Comment by bknowles** [comment]
Maybe including the apache checklists at https://web.nvd.nist.gov/view/ncp/repository ?

**Comment by konklone** [comment]
Could be worth linking to, though I [don't see any listings for Apache 2.4](https://web.nvd.nist.gov/view/ncp/repository?keyword=apache&startIndex=0).

**Comment by bknowles** [comment]
No, regretfully they're a bit slow.  The national checklists can only be updated when someone submits a checklist, usually from a vendor (like the Red Hat checklist for JBOSS), or maybe an agency or someone else that wants to get some standard set.  And it takes a while to get them through the process.  Still, that's the official source of national checklists, and it should probably be referenced even if it is a bit out-of-date.

**Comment by bknowles** [comment]
CIS does have an Apache 2.4 benchmark, which you can download from https://benchmarks.cisecurity.org but that's just the PDF version.  If you want to download the version you can feed to a SCAP tool, you have to be a CIS member.

**Comment by bknowles** [comment]
Of course, there's all the other HTTP server implementations out there as well, including tomcat, JBOSS, and so on.

**Comment by konklone** [comment]
Closing in favor of #30.
