### ISSUE TITLE
What should be required vs. recommended?  

### ISSUE THREAD

**Issue by gbinal** [GSA/https#5]
For discussion...

**Comment by gbinal** [comment]
Also to consider: in what timeframe?

**Comment by gbinal** [comment]
Offhand, I'd say HTTPS should be required to work (perhaps within 8-12 months), but that forcing HTTPS and HSTS should be recommended.

**Comment by konklone** [comment]
To be honest, I don't think the requirement would do much if HTTPS weren't forced. (And if HTTPS is forced, then HSTS is trivial to add.) I'd much rather be more generous on the timeframe for outfitting existing sites than weaken the outcome that's being asked for.

There's also the distinction between existing and new sites. The cost of HTTPS for new sites is so low, that I think requiring forced HTTPS (and HSTS) for new sites is, from the perspective of operations and burden, an easy win.

**Comment by gbinal** [comment]
Interesting.  I'm definitely open to required for new (and renovated sites), and think it makes sense to discuss requiring vs. encouraged forced for existing sites and over what timetable.

**Comment by NoahKunin** [comment]
Yeah, from a technical level, allowing HTTP to still work opens up both real and potential vulnerabilities. Was just mapping out an attack model based on that the other day.

On #1 I'm in total alignment on a total requirement for new sites, and a 1-year window after that (or some other time period) for sites created before the mandate.

**Comment by konklone** [comment]
This conversation has moved to other fora, and I'd like the issue tracker now to focus on the work that needs to be done on this website.
