### ISSUE TITLE
Compliance guide

### ISSUE THREAD

**Issue by konklone** [GSA/https#53]
One page that just goes down, piece by piece, what you should do to meet this guidance's standards. In response to an email I got today, asking me for that.

**Comment by alex** [comment]
Items for the checklist (in no particular order):

* Purchase certificate
* Install certificate
* Redirect HTTP to HTTPS
* Add HSTS
* Repeat for subdomains
* Add `includeSubDomains` to HSTS
* Check for mixed content across the entire site
* Configure whatever's terminating TLS to make sure cipher suites and such are good
* In a multi-server environment figure out what to do about session IDs/ tickets
*

**Comment by gbinal** [comment]
:+1:

**Comment by pwnall** [comment]
I think it'd be helpful to include a pointer to a SSL testing service, such as https://www.ssllabs.com/ssltest/

Ideally, it'd be open-sourced on GitHub, so it can be verified and updated. The example that I gave above  isn't open source, but it seems to be reasonably thorough, so it's a start.

**Comment by bknowles** [comment]
How about we refer people to the tools at https://https.cio.gov/resources/ ?

**Comment by gbinal** [comment]
Would it make sense to do 2 variants - One for new sites and one for existing sites that need to transition?  

Since the policy calls out the need for new sites to have from day one, that's a pressing use case that we should try to support as thoroughly and specifically as possible.

**Comment by konklone** [comment]
Good call.

**Comment by konklone** [comment]
Renaming this issue to focus on being a one-page Compliance Guide. It may well need to be broken out into two pages for new vs existing, but I suspect it won't be necessary.

This is where we'll put information about preloading vs subdomains, and describing/linking to the migration process.

**Comment by konklone** [comment]
This got done in #133.
