### ISSUE TITLE
Require 'secure' flag on cookies

### ISSUE THREAD

**Issue by aneeshusa** [GSA/https#77]
Would it be in the scope of this proposal to require all cookies to have the "Secure" flag set, if any cookies are needed? It would further cement the "HTTPS is required" message and I think it would be a great addition.

The Mixed Content page does mention issues with mixed content and cookies, but I think the best place for info about this would be the Migrating APIs to HTTPS page. I can work on a PR if this is a reasonable addition to the proposal.

**Comment by anandbhat2509** [comment]
:+1:

**Comment by mcatanzaro** [comment]
Secure cookies should be required even though HSTS is also required, since HSTS policies expire. Also, using secure cookies provides moderate protection to browsers that do not understand HSTS.

**Comment by konklone** [comment]
I'm a big fan of secure cookies, but I also _personally_ think it's out of scope for the work here. There are other good web security practices, like XSS protection and iframe policies, that help websites do better by users, but which just aren't part of deploying HTTPS. Open to hearing other opinions by the project team here.

> Secure cookies should be required even though HSTS is also required, since HSTS policies expire. Also, using secure cookies provides moderate protection to browsers that do not understand HSTS.

FWIW, the policy and guidance encourage (but don't mandate) full HSTS preloading, which would make policies not expire. Additionally, with IE [now supporting HSTS](http://caniuse.com/#search=hsts), browser support is or soon will be near-universal.

**Comment by gbinal** [comment]
+1, @konklone.  It'll help to keep the scope focused.

**Comment by konklone** [comment]
Closing as out of scope for this work (much as I support secure cookies).
