### ISSUE TITLE
Yes, Yes, and Another Yes!

### ISSUE THREAD

**Issue by dstufft** [GSA/https#78]
This is *great*, I'm super excited to see this proposal and to see the federal government taking online privacy/security seriously.

**Comment by frewsxcv** [comment]
I agree with @dstufft. Moving forward with this initiative will push the US Federal government ahead of not only the private sector, but many other foreign governments. A more secure internet is a better internet. :lock:

**Comment by etrepum** [comment]
Totally agree, I think this is an excellent idea and I would really like to see it happen.
