### ISSUE TITLE
Applicability to non-executive branch websites?

### ISSUE THREAD

**Issue by gmcharlt** [GSA/https#88]
First, kudos for this proposal.  An extra benefit I see arising merely from its existence is encouraging state and local government agencies to also go HTTPS-only.

Here's my (no doubt naive) question: if this proposal gets approved and implemented, would it automatically apply to non-executive branch websites (house.gov, loc.gov, supremecourt.gov, etc.)?  Or would those agencies currently be free to ignore HTTPS if they so chose?  What about public .mil sites?

**Comment by cherrypj** [comment]
It looks like this proposed initiative, “The HTTPS-Only Standard,” would require the use of HTTPS on all publicly accessible Federal websites and web services.
