### ISSUE TITLE
A much-needed bar-raising

### ISSUE THREAD

**Issue by svitka** [GSA/https#96]
Aside from the copious security benefits of doing this, modernizing federal websites through the (mandatory) adoption of HTTPS will represent a sea-change. There are two scenarios in which this will be evident:
1) The federal government moves forward with this policy, implementation is at least smooth enough, interactions with the federal government become safer, and – perhaps most importantly – other actors that are also lagging in implementing HTTPS have to reflect on the despair-inducing fact that they are behind the federal government in technological terms. For instance, the advertising industry is in desperate need of securing the information it transmits among hundreds of other actors, especially given that they serve as a leaky faucet for every website in which their ads are displayed. (See, e.g., https://openeffect.ca/some-impressions-on-internet-advertiser-security/). And then, maybe, they'll also take this step, for the same reason that the federal government should now.
-OR-
2) The federal government becomes one of the last major actors to utilize HTTPS (among governments, or when compared to industry), at which point it will be yet another apathy-inducing, groan-worthy anecdote about how dangerously and expensively slow the federal government is at modernizing.

I personally long for the former – where I can point to the federal government as the leader.

A final note: when it comes to questions of cost, which are certainly valid and should be considered, do we not all expect this to happen *at some point*? The cost is now or later – with the public's privacy and security (both directly regarding federal sites and in secondary effects as described above) at risk in between.

Respectfully,
Sean Vitka

(Secret message: Can we all note how freaking awesome it is that you're soliciting feedback via GitHub? The number of people who don't think they can engage government on important issues simply for the sheer Luddism of formal process is stunning – kudos to all of you doing this out in the open!)

**Comment by ErieMeyer** [comment]
(Secret message received!)
